const AppRoute = {
  ROOT: "/",
  SIGN_IN: "/sign-in",
  SIGN_UP: "/sign-up",
  SIGN_UP_ADDITIONAL_INFO: "/sign-up/additional-info",
  SIGN_UP_INTERESTS: "/sign-up/interests",
  FORGOT_PASSWORD: "/sign-up/forgot-password",
  TEAMS_$ID: "/teams/:id",
  TEAMS_$ID_DESCRIPTION: "/teams/:id/description",
  TEAMS_$ID_MEMBERS: "/teams/:id/members",
  TEAMS_$ID_FORUM: "/teams/:id/forum",
  TEAMS: "/teams",
  TEAMS_CURRENT: "/teams/current",
  TEAMS_COMPLETED: "/teams/completed",
  MY_TEAMS: "/my-teams",
  MY_TEAMS_CURRENT: "/my-teams/current",
  MY_TEAMS_COMPLETED: "/my-teams/completed",
  NOTIFICATIONS: "/notifications",
  PROFILE_$ID: "/profile/:id",
  PROFILE_$ID_INTERESTS: "/profile/:id/interests",
  PROFILE_$ID_SOCIAL_MEDIA: "/profile/:id/social-media",
  PROFILE_$ID_EDIT_PROFILE: "/profile/:id/edit-profile",
} as const;

export { AppRoute };
