const AppRoute = {
  ROOT: "/",
  SIGN_IN: "/sign-in",
  SIGN_UP: "/sign-up",
  SIGN_UP_ADDITIONAL_INFO: "/sign-up/additional-info",
  SIGN_UP_INTERESTS: "/sign-up/interests",
  FORGOT_PASSWORD: "/sign-up/forgot-password",
  EVENTS_$ID: "/events/:id",
  EVENTS_$ID_DESCRIPTION: "/events/:id/description",
  EVENTS_$ID_MEMBERS: "/events/:id/members",
  EVENTS_$ID_FORUM: "/events/:id/forum",
  EVENTS: "/events",
  EVENTS_CURRENT: "/events/current",
  EVENTS_COMPLETED: "/events/completed",
  MY_EVENTS: "/my-events",
  MY_EVENTS_CURRENT: "/my-events/current",
  MY_EVENTS_COMPLETED: "/my-events/completed",
  NOTIFICATIONS: "/notifications",
  PROFILE_$ID: "/profile/:id",
  PROFILE_$ID_INTERESTS: "/profile/:id/interests",
  PROFILE_$ID_SOCIAL_MEDIA: "/profile/:id/social-media",
  PROFILE_$ID_EDIT_PROFILE: "/profile/:id/edit-profile",
} as const;

export { AppRoute };
